name: release

env:
  DENO_VERSION: 1.x

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Publish
        run: deno publish

  release:
    needs:
      - jsr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno run -A npm:changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
